import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import device1 from "../public/1.jpg";
import device2 from "../public/2.jpg";
import device3 from "../public/3.jpg";
import device4 from "../public/4.jpg";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {faTriangleExclamation } from "@fortawesome/free-solid-svg-icons";
export default function Home() {
  return (
    <div className={styles.Home}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.container}>
          <h5><FontAwesomeIcon />ProSmart</h5>
          <h1 className={styles.title}>Modern Smart Compact Projector</h1>

          <p className={styles.description}>
            Lorem Ipsum is simply dummy text of the printing and typesetting
            industry. Lorem Ipsum has been the industry's standard dummy text
            ever since the 1500s
          </p>

          <h1>Experience</h1>
          <p className={styles.experience}> Enhance your Experience with the best movies, get 1 year free with the purchase of prosmart</p>
          <button className={styles.btn_buy}>Buy Now</button>
       
        </div>
        <div className={styles.images}>
          <aside>
            {" "}
            <Image src={device4}  className={styles.Image} height="600px" width="400px" priority/>{" "}
            <Image src={device2}  className={styles.Image} height="380px" width="400px" priority  />
          </aside>
          <aside>
            {" "}
            <Image src={device1}  className={styles.Image}  height="380px" priority/>{" "}
            <Image src={device3}  className={styles.Image}  height="600px" width="400px" priority />
          </aside>
        </div>
      </main>

     
    </div>
  );
}
